### ISSUE TITLE
error while processing images

### ISSUE THREAD

**Issue by mezelve** [stavsap/ComfyUI-Discord-Bot#3]
Hi, I've changed the txt2img wf to a Flux Dev one. It generates images in my Comfy output folder, but the result doesn't show up in the discord chat. Error message: "error while processing images".
I know it must be something with handle_prompt_queue_result in comfy_bot.py
What am I overlooking here? Thanks

**Comment by stavsap** [comment]
i have add handler for flux ing2txt few days ago

https://github.com/stavsap/ComfyUI-Discord-Bot/blob/2954ae8dac31a1791f17df1d1c64743dbffb4ec4/handlers/handlers.py#L1057

i can take it as a reference.

https://github.com/stavsap/ComfyUI-Discord-Bot/blob/2954ae8dac31a1791f17df1d1c64743dbffb4ec4/handlers/prompts.py#L867

https://github.com/stavsap/ComfyUI-Discord-Bot/blob/main/.meta/workflows/flux_schnell.json
